---
repos:

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - name: check YAML format
        id: yamllint

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - name: re-format with black
        id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - name: remove whitespaces
        id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 21d3c70d676007470908d39b73f0521d39b3b997
    hooks:
      - name: check-format with flake8
        id: flake8
