---
repos:

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - name: check YAML format
        id: yamllint

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - name: re-format with black
        id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - name: remove whitespaces
        id: trailing-whitespace
      - name: add newline to end of files
        id: end-of-file-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - name: check-format with flake8
        id: flake8
