language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

matrix:
  include:
    - python: "2.7"
      env: TMODE=flake8
env:
    TMODE=test

install:
  - "if [[ $TMODE == 'test' ]]; then pip install pytest; fi"
  - "if [[ $TMODE == 'test' ]]; then python setup.py install; fi"
  - pip freeze
  - ls -lh .eggs || true

script:
  - python setup.py $TMODE
  - "if [[ $TMODE == 'test' ]]; then python setup.py sdist bdist_wheel; fi"

after_success:
  - "if [[ $TMODE == 'test' ]]; then coveralls; fi"

notifications:
  email:
    on_success: change
    on_failure: change
