language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

matrix:
  include:
    - python: "3.6"
      env: TMODE=flake8
env:
    TMODE=test

install:
  - "if [[ $TMODE == 'test' ]]; then pip install pytest; fi"
  - "if [[ $TMODE == 'test' ]]; then python setup.py install; fi"
  - pip freeze --all
  - ls -lh .eggs || true

script:
  - python setup.py $TMODE

after_success:
  - "if [[ $TMODE == 'test' ]]; then pip install python-coveralls; coveralls; fi"

notifications:
  email:
    on_success: change
    on_failure: change
